### ISSUE TITLE
We don't return indico errors gracefully

### ISSUE THREAD

**Issue by anneCarlson** [IndicoDataSolutions/IndicoIo-python#124]

**Comment by anneCarlson** [comment]
With a locked api_key:
```indicoio.sentiment("indico is so easy to use!")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/indicoio/__init__.py", line 44, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/indicoio/text/sentiment.py", line 52, in posneg
    return api_handler(text, cloud=cloud, api="sentiment", url_params=url_params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/indicoio/utils/api.py", line 27, in api_handler
    json_results = response.json()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by madisonmay** [comment]
We do -- this was a special case where IndicoAPI was returning the wrong response.
