### ISSUE TITLE
setup.py chokes on numpy & six requirement

### ISSUE THREAD

**Issue by MattTheRed** [IndicoDataSolutions/IndicoIo-python#14]
When installing on a mac in a virtualenv (using virtualenv wrapper), installation of numpy ostensibly succeeds, but then is not available for future requirements that depend on it. Seems related to this bug: https://github.com/numpy/numpy/issues/2434 
```
Downloading/unpacking scikit-image>=0.10.1 (from indicoio)
  Downloading scikit-image-0.10.1.tar.gz (16.7Mb): 16.7Mb downloaded
  Running setup.py egg_info for package scikit-image
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/Users/mattthered/.virtualenvs/indico/build/scikit-image/setup.py", line 37, in <module>
        from numpy.distutils.core import setup
    ImportError: No module named numpy.distutils.core
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/Users/mattthered/.virtualenvs/indico/build/scikit-image/setup.py", line 37, in <module>

    from numpy.distutils.core import setup

ImportError: No module named numpy.distutils.core

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /Users/mattthered/.virtualenvs/indico/build/scikit-image
Storing complete log in /Users/mattthered/.pip/pip.l
```

**Comment by madisonmay** [comment]
Fixed this a while back but forgot to close it, thanks for reporting!
