### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by Slater-Victoroff** [IndicoDataSolutions/IndicoIo-python#72]
Requests and Pillow aren't included in a clean install, had to install them myself on new computer

**Comment by Slater-Victoroff** [comment]
Specific Error Tracebacks:

  InsecurePlatformWarning
  Downloading IndicoIo-0.7.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-cM5kE3/indicoio/setup.py", line 4, in <module>
        from indicoio import VERSION
      File "indicoio/__init__.py", line 12, in <module>
        from indicoio.text.sentiment import political, posneg, sentiment_hq
      File "indicoio/text/sentiment.py", line 1, in <module>
        from indicoio.utils.api import api_handler
      File "indicoio/utils/api.py", line 5, in <module>
        import json, requests
    ImportError: No module named requests

  Downloading IndicoIo-0.7.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-lBIWIp/indicoio/setup.py", line 4, in <module>
        from indicoio import VERSION
      File "indicoio/__init__.py", line 16, in <module>
        from indicoio.images.fer import fer
      File "indicoio/images/fer.py", line 4, in <module>
        from indicoio.utils.image import image_preprocess
      File "indicoio/utils/image.py", line 7, in <module>
        from PIL import Image
    ImportError: No module named PIL

**Comment by Slater-Victoroff** [comment]
Ah, figured out the problem. importing VERSION has requirements.

**Comment by madisonmay** [comment]
Fixed in #73.
